### ISSUE TITLE
When you gonna upgrade json-schema-faker lib to 0.4.6 ?

### ISSUE THREAD

**Issue by AbdoDabbas** [json-schema-faker/json-schema-server#18]
I was wondering when you gonna upgrade json-schema-faker lib to 0.4.6 ?

I cloned the project and upgrade it, but was not able to build it in order to make sure every thing is ok.
What is the build command ?

**Comment by pateketrueke** [comment]
Hi, I just released `0.4.0` for solving this.

Thanks for your feedback!
